fixtures:
  repositories:
    stdlib:        "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:
      repo: 'git://github.com/puppet-community/puppet-extlib'
      ref:  'v0.11.3'
    apache:        "git://github.com/puppetlabs/puppetlabs-apache.git"
    postgresql:    "git://github.com/puppetlabs/puppetlabs-postgresql.git"
    mongodb:       "git://github.com/puppetlabs/puppetlabs-mongodb.git"
    foreman:       "git://github.com/theforeman/puppet-foreman.git"
    concat:        "git://github.com/puppetlabs/puppetlabs-concat.git"
    certs:         "git://github.com/katello/puppet-certs.git"
    common:        "git://github.com/katello/puppet-common.git"
    qpid:          "git://github.com/katello/puppet-qpid.git"
    candlepin:     "git://github.com/katello/puppet-candlepin.git"
    pulp:          "git://github.com/katello/puppet-pulp.git"
    squid3:        "git://github.com/thias/puppet-squid3.git"
  symlinks:
    katello: "#{source_dir}"
