fixtures:
  repositories:
    apache:        "https://github.com/puppetlabs/puppetlabs-apache.git"
    augeas_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-augeas_core'
      puppet_version: '>= 6.0.0'
    candlepin:     "https://github.com/theforeman/puppet-candlepin.git"
    certs:         "https://github.com/theforeman/puppet-certs.git"
    concat:        "https://github.com/puppetlabs/puppetlabs-concat.git"
    cron_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-cron_core'
      puppet_version: '>= 6.0.0'
    extlib:        "https://github.com/voxpupuli/puppet-extlib"
    foreman:       "https://github.com/theforeman/puppet-foreman.git"
    postgresql:    "https://github.com/puppetlabs/puppetlabs-postgresql.git"
    qpid:          "https://github.com/theforeman/puppet-qpid.git"
    redis:         "https://github.com/voxpupuli/puppet-redis"
    selinux:       "https://github.com/voxpupuli/puppet-selinux.git"
    selinux_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-selinux_core'
      puppet_version: '>= 6.0.0'
    stdlib:        "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd:       "https://github.com/voxpupuli/puppet-systemd.git"
    yumrepo_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core'
      puppet_version: '>= 6.0.0'
