fixtures:
  repositories:
    stdlib:        "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:        "https://github.com/puppet-community/puppet-extlib"
    apache:        "https://github.com/puppetlabs/puppetlabs-apache.git"
    postgresql:    "https://github.com/puppetlabs/puppetlabs-postgresql.git"
    mongodb:       "https://github.com/puppetlabs/puppetlabs-mongodb.git"
    foreman:       "https://github.com/theforeman/puppet-foreman.git"
    concat:        "https://github.com/puppetlabs/puppetlabs-concat.git"
    certs:         "https://github.com/theforeman/puppet-certs.git"
    qpid:          "https://github.com/theforeman/puppet-qpid.git"
    candlepin:     "https://github.com/theforeman/puppet-candlepin.git"
    pulp:          "https://github.com/theforeman/puppet-pulp.git"
    squid3:        "https://github.com/thias/puppet-squid3.git"
  symlinks:
    katello: "#{source_dir}"
